### ISSUE TITLE
Feature Request: 'Message' option for phone numbers instead of just "Call"

### ISSUE THREAD

**Issue by ajones55555** [jefelewis/react-native-contact-action-sheet#1]
It would be cool if there was also support for a "Text Message" option that could open the platforms' respective messaging app.

That way you could do something like the native iOS Contact Action sheet, which shows "Call" or "Text" when you click on a phone number (ie user clicks on "123-456-7890" and it asks to Call 1234567890 or Text 1234567890)

**Comment by jefelewis** [comment]
@aej11a I've included 'Message' in the newest version 0.0.3 and it looks something like this:

![Simulator Screen Shot - iPhone 11 - 2020-01-31 at 09 16 41](https://user-images.githubusercontent.com/26728487/73560084-2ab42700-440b-11ea-8b1a-8d67dff8984e.png)
